/**
 * TruthSerum Core Types
 * All interfaces and types for verification, proofs, and audit trails
 */

// ============================================================================
// VERIFICATION PRIMITIVE (Base Type for All Truth-Bearing Entities)
// ============================================================================

export type VerificationMethod =
  | 'source_import'      // Imported from authenticated source
  | 'scholar_reviewed'   // Verified by human scholar
  | 'cross_referenced'   // Verified against multiple sources
  | 'system_generated'   // Generated by system (lower trust)
  | 'user_contributed'   // User-contributed (requires review)

export interface VerificationPrimitive {
  // Content integrity
  content_hash: string            // SHA-256 of canonical content (deterministic)
  content_version: number         // Monotonic version counter

  // Source attribution
  source_id: string               // Immutable reference to source artifact
  source_hash: string             // SHA-256 of original source document
  source_page?: string            // Physical page reference if applicable

  // Verification metadata
  verification_method: VerificationMethod
  verified_at: string             // ISO 8601 timestamp
  verified_by: string             // system | scholar:{id} | import:{pipeline_id}

  // Audit trail
  verification_signature: string  // HMAC-SHA256(content_hash + source_hash + verified_at, SECRET)
  previous_hash?: string          // Hash of previous version (for audit chain)
}

// ============================================================================
// PROOF RECEIPT (Single Standard for All Operations)
// ============================================================================

export type OperationType =
  | 'GET_HADITH'
  | 'SEARCH_HADITH'
  | 'AI_EXPLAIN'
  | 'SAFETY_CHECK'
  | 'USER_SAVE'
  | 'CREATE_NOTE'
  | 'VERIFY_CONTENT'
  | 'COUNT_HADITH'

export type ConfidenceLevel =
  | 'verified'        // 100% - All sources checked and verified
  | 'high'           // 95%+ - Sources checked, minor gaps
  | 'medium'         // 80%+ - Most sources checked
  | 'low'            // <80% - Limited verification
  | 'unverified'     // 0% - No verification performed

export interface ProofReceipt<TInput = unknown, TOutput = unknown> {
  // Operation identity
  receipt_id: string              // UUID v4
  operation: OperationType        // What was done
  operation_version: string       // API version (e.g., "v1.0.0")

  // Request context
  request_id: string              // Trace ID for debugging
  timestamp: string               // ISO 8601 when operation started
  duration_ms: number             // How long operation took

  // Inputs (what was requested)
  inputs: {
    hash: string                  // SHA-256 of input parameters
    params: TInput                // Actual input (sanitized of PII)
  }

  // Outputs (what was returned)
  outputs: {
    hash: string                  // SHA-256 of output data
    count: number                 // Number of entities returned
    entity_ids: string[]          // IDs of entities (for audit trail)
  }

  // Verification proof
  verification: {
    all_verified: boolean         // Were ALL outputs verified?
    verified_count: number        // How many entities passed verification
    unverified_count: number      // How many could not be verified
    verification_failures?: {     // If any failed, why?
      entity_id: string
      reason: string
    }[]
  }

  // Truth attestation
  attestation: {
    signature: string             // HMAC-SHA256 of entire receipt
    signer: string                // service:{name} | user:{id}
    confidence: ConfidenceLevel   // How confident are we?
  }

  // Audit trail link
  audit_log_id: string            // Reference to append-only log entry
  previous_receipt_id?: string    // Link to previous receipt (if chained operation)
}

// ============================================================================
// TRUTH-BEARING ENTITIES
// ============================================================================

export type HadithGrade =
  | 'sahih'          // Authentic
  | 'hasan'          // Good
  | 'daif'           // Weak
  | 'mawdu'          // Fabricated

export interface Hadith extends VerificationPrimitive {
  // Identity
  id: string                      // UUID v4
  hadith_number: number           // Sequential number within collection

  // Content (canonical form)
  arabic_text: string             // Original Arabic (normalized)
  english_translation: string     // Primary translation

  // Attribution
  collection: string              // Sahih Bukhari, Sahih Muslim, etc.
  book: string                    // Book within collection
  chapter: string                 // Chapter within book

  // Narrator chain (isnad)
  narrator_chain: string[]        // Full chain from Prophet to compiler
  narrator_chain_hash: string     // Hash of complete chain (for integrity)

  // Grading
  grade: HadithGrade
  grade_source: string            // Who graded it (scholar name/org)
  grade_reasoning?: string        // Why this grade (optional)

  // Metadata
  created_at: string
  updated_at: string
  version: number                 // Content version (increments on edit)
}

export interface Citation {
  hadith_id: string               // Which hadith was cited
  hadith_hash: string             // Hash at time of citation (immutable proof)
  excerpt: string                 // Specific text cited
  relevance: 'primary' | 'supporting' | 'contextual'
}

export interface AIExplanation extends VerificationPrimitive {
  // Identity
  id: string                      // UUID v4
  hadith_id: string               // Reference to source hadith

  // Content
  explanation: string             // AI-generated explanation
  explanation_hash: string        // Hash of explanation text

  // Sources (REQUIRED - no explanation without sources)
  citations: Citation[]
  citation_coverage: number       // % of explanation backed by citations (target: 100%)

  // Model metadata
  model: string                   // gpt-4, gpt-3.5-turbo, etc.
  model_version: string           // Exact version for reproducibility
  temperature: number             // Generation params
  tokens_used: number

  // Safety check
  safety_check: {
    passed: boolean
    patterns_triggered: string[]
    blocked_content?: string      // If filtered, what was removed
  }

  // Metadata
  created_at: string
  regenerated_count: number       // How many times regenerated
}

export interface PatternMatch {
  pattern_id: string              // Which pattern matched
  pattern_category: string        // Category (sectarianism, violence, etc.)
  match_text: string              // What text matched
  severity: 'low' | 'medium' | 'high' | 'critical'
}

export interface SafetyDecision extends VerificationPrimitive {
  // Identity
  id: string                      // UUID v4
  query_hash: string              // Hash of input query

  // Input
  query: string                   // User's query (sanitized)
  query_metadata: {
    language: string
    length: number
    contains_arabic: boolean
  }

  // Decision
  decision: 'allowed' | 'blocked'
  confidence: number              // 0-1, how confident in decision

  // Pattern matching
  patterns_matched: PatternMatch[]
  total_patterns_checked: number

  // Outcome tracking
  false_positive_flagged: boolean // Did user report false positive?
  reviewed_by_human: boolean      // Did human review this decision?
  review_outcome?: 'correct' | 'incorrect' | 'unclear'

  // Metadata
  created_at: string
  user_id?: string                // If logged in
  session_id: string              // Anonymous session
}

// ============================================================================
// AUDIT LOG (Append-Only)
// ============================================================================

export interface AuditLogEntry {
  id: string                      // UUID v4
  receipt: ProofReceipt
  created_at: string              // ISO 8601
}

// ============================================================================
// SAFETY METRICS (Real-Time Effectiveness)
// ============================================================================

export interface SafetyMetrics {
  id: string                      // UUID v4
  metric_date: string             // YYYY-MM-DD

  // Volume
  total_queries: number
  blocked_queries: number
  allowed_queries: number

  // Accuracy (requires human review)
  false_positives: number
  false_negatives: number
  true_positives: number
  true_negatives: number

  // By category
  blocked_by_category: Record<string, number>

  // Effectiveness
  precision?: number              // true_positives / (true_positives + false_positives)
  recall?: number                 // true_positives / (true_positives + false_negatives)
  f1_score?: number               // 2 * (precision * recall) / (precision + recall)

  // Computed
  updated_at: string
}

// ============================================================================
// ERROR TYPES
// ============================================================================

export class UnverifiedContentError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'UnverifiedContentError'
  }
}

export class IntegrityViolationError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'IntegrityViolationError'
  }
}

export class NoCitationError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'NoCitationError'
  }
}

export class ReceiptNotFoundError extends Error {
  constructor(receiptId: string) {
    super(`Receipt not found: ${receiptId}`)
    this.name = 'ReceiptNotFoundError'
  }
}

export class TamperedReceiptError extends Error {
  constructor(receiptId: string) {
    super(`Receipt signature invalid (possibly tampered): ${receiptId}`)
    this.name = 'TamperedReceiptError'
  }
}
